#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_motion_interval 0
bspc config focused_border_color "#87AFFF"
bspc config normal_border_color "#161616"

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
polybar -r &
picom &
/usr/lib/geoclue-2.0/demos/agent &
redshift &
